version: '3.5'

networks:
  db:
  workstation:
  farm:

services:

  # render farm
  deadline-server:
    hostname: server
    image: localhost:5000/deadline-server
    environment:
      MONGO: deadline-db
      MONGO_PORT: "27017"
    build:
      context: ./src
      dockerfile: Dockerfile
      target: server
    networks:
      - farm
      - workstation
      - db

  deadline-worker:
    image: localhost:5000/deadline-worker
    hostname: worker
    build:
      context: ./src
      dockerfile: Dockerfile
      target: client
    networks:
      - farm
      - db

  deadline-db:
    image: mongo
    networks:
      - db

  # workstations
  polaris:
    hostname: polaris
    image: localhost:5000/polaris
    networks:
      - workstation
    env_file:
      - .env
    build:
      context: ./src
      dockerfile: Dockerfile
      target: workstation

  viewer:
    hostname: novnc
    image: dougw/novnc
    networks:
      - workstation
    ports:
      - "8081:8081"
    environment:
      REMOTE_HOST: "polaris"
      REMOTE_PORT: "5901"
