apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deadline-workers
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: deadline-workers

  template:
    metadata:
      labels:
        app: deadline-workers

    spec:
      nodeSelector:
        render: "true"

      containers:
        - name: deadline-worker
          image: {{ .Values.farm.worker_image }}
          imagePullPolicy: Always
