apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadline-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: deadline-server
  template:
    metadata:
      labels:
        app: deadline-server

    spec:
      nodeSelector:
        services: "true"

      containers:
        - name: deadline-server
          image: {{ .Values.farm.server_image }}
          imagePullPolicy: Always
          env:
            - name: MONGO
              value: "deadline-mongo"
            - name: MONGO_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: deadline-server
spec:
  selector:
    app: deadline-server
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: deadline-server
