apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadline-mongo
  namespace: prod
spec:
  selector:
    matchLabels:
      app: deadline-mongo

  template:
    metadata:
      labels:
        app: deadline-mongo

    spec:
      containers:
        - name: deadline-mongo
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: "mongo-port"
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: deadline-mongo
spec:
  selector:
    app: deadline-mongo
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: db-port
