apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris
  namespace: prod
spec:
  selector:
    matchLabels:
      app: polaris

  template:
    metadata:
      labels:
        app: polaris

    spec:
      containers:
        - name: polaris
          image: localhost:5000/polaris
          imagePullPolicy: Always
          env:
            - name: USER
              value: "bob"
            - name: PASSWORD
              value: "testing"
            - name: SUDO
              value: "true"

        - name: polaris-viewer
          image: dougw/novnc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: viewer
          env:
            - name: REMOTE_HOST
              value: "localhost"
            - name: REMOTE_PORT
              value: "5901"
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: polaris
spec:
  selector:
    app: polaris
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: vnc
